version: '3'
services:
  udagram-user:
    build: 
      context: udagram-api-user
      dockerfile: Dockerfile
    image: tuannns99/udgram-api-user
  udagram-feed:
    build: 
      context: udagram-api-feed
      dockerfile: Dockerfile
    image: tuannns99/udgram-api-feed
  reverseproxy:
    build: 
      context: .
      dockerfile: Dockerfile
    image: tuannns99/reverseproxy
  udagram-frontend:
    build: 
      context: udgram-frontend
      dockerfile: Dockerfile
    image: tuannns99/udgram-frontend